In [16]:
import numpy as np
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])
square1=np.sort(square, axis=0)
squareT=square1.T
con1=np.hstack((square1, squareT))
con2=np.vstack((square1, squareT))
con3=np.concatenate((square1, squareT), axis=None)
print(square1)
print(squareT)
print(con1)
print(con2)
print(con3)

[[ 4  3  2  1]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [16 15 14 13]]
[[ 4  5  9 16]
 [ 3  6 10 15]
 [ 2  7 11 14]
 [ 1  8 12 13]]
[[ 4  3  2  1  4  5  9 16]
 [ 5  6  7  8  3  6 10 15]
 [ 9 10 11 12  2  7 11 14]
 [16 15 14 13  1  8 12 13]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [16 15 14 13]
 [ 4  5  9 16]
 [ 3  6 10 15]
 [ 2  7 11 14]
 [ 1  8 12 13]]
[ 4  3  2  1  5  6  7  8  9 10 11 12 16 15 14 13  4  5  9 16  3  6 10 15
  2  7 11 14  1  8 12 13]


In [27]:
import numpy as np
def optimize(mas):
    minimum=min(mas)
    maximum=max(mas)
    if minimum>=0:
        minus=False
    else:
        minus=True
    if minus:
        nmin=int(-np.log2(abs(minimum)+1))
        nmax=int(np.log2(maximum+1)+1)
        n=max(nmin, nmax)
    else:
        n=int(np.log2(maximum+1))
    if minus:
        if n<=8:
            M=np.array(mas, dtype=np.int8)
        elif n<=16:
            M=np.array(mas, dtype=np.int16)
        elif n<=32:
            M=np.array(mas, dtype=np.int32)
        else:
            M=np.array(mas, dtype=np.int64)
    else:
        if n<=8:
            M=np.array(mas, dtype=np.uint8)
        elif n<=16:
            M=np.array(mas, dtype=np.uint16)
        elif n<=32:
            M=np.array(mas, dtype=np.uint32)
        else:
            M=np.array(mas, dtype=np.uint64)
    return M, n
mas=[]
for i in range (10):
    m=int(input())
    mas.append(m)
Arr, n=optimize(mas)
print(Arr)

1000
1000
1
-1
2
2000
1234
234
123
134
[1000 1000    1   -1    2 2000 1234  234  123  134] 11


In [41]:
import numpy as np
f=open('Cell_culture.txt')
def read(file):
    mas=file.readlines()
    leng=len(mas)
    imas=[[0]*4 for i in range (leng-1)]
    for i in range (1, leng):
        for j in range (4):
            imas[i-1][j]=mas[i].strip().split('\t')[j]
    imas=np.array(imas)
    imas=np.array(imas, dtype=[('Date', str, 6), ('Name', str, 5), ('Volume', int), ('Comment', str, 15)])
    return imas
M=read(f)
print(M)

ValueError: invalid literal for int() with base 10: '5-Apr'